#!/usr/bin/env bash
echo "export ZDOTDIR=~/.config/zsh" >~/.zshenv
SUBMODULES=$(git config --file .gitmodules --get-regexp '^submodule\..*\.path$' | awk '{print $2}' | tr '\n' ' ')
for SUBMODULE in $SUBMODULES; do
  if [ ! -d "$SUBMODULE"/.git ]; then
    git submodule init
    git submodule update --remote --recursive
  fi
done
