#!/usr/bin/env bash
set -euo pipefail
# ARRAYS
declare -A app_cred=(
  [az]="tenant"
  [bw]="addr clientid clientsecret master"
  [ssh]="passwd"
  [vault]="addr user passwd"
)
# FUNCTIONS
cred_check() {
  for sec in ${app_cred["$1"]}; do
    if [[ -z ${2:-} ]]; then
      if ! pass "$1"/"$sec" &>/dev/null; then
        pass insert "$1"/"$sec"
      fi
    else
      if ! pass "$1"/"${2:-}"/"$sec" &>/dev/null; then
        pass insert "$1"/"${2:-}"/"$sec"
      fi
    fi
  done
}
cred_path() {
  if [[ -z ${3:-} ]]; then
    printf '%s/%s' "$1" "$2"
  else
    printf '%s/%s/%s' "$1" "${3:-}" "${2:-}"
  fi
}
cred_cmd() {
  if [[ -z ${3:-} ]]; then
    pass "$(cred_path $1 $2)"
  else
    pass "$(cred_path $1 $2 "${3:-}")"
  fi
}
# LOGINS
bw_login() {
  BITWARDENCLI_APPDATA_DIR=$HOME/.config/bw
  cred_check "$1" "${2:-}"
  if [[ ! -d $BITWARDENCLI_APPDATA_DIR ]]; then
    bw config server "$(cred_cmd $1 addr "${2:-}")"
  elif bw login --check &>/dev/null && ! grep "$(cred_cmd $1 addr "${2:-}")" $BITWARDENCLI_APPDATA_DIR/data.json &>/dev/null; then
    bw logout
    bw config server "$(cred_cmd $1 addr "${2:-}")"
  fi
  if ! bw login --check; then
    BW_CLIENTID="$(cred_cmd $1 clientid "${2:-}")" \
    BW_CLIENTSECRET="$(cred_cmd $1 clientsecret "${2:-}")" \
      bw login --apikey --raw
    bw_master="$(cred_cmd $1 master "${2:-}")" \
    bw unlock --raw --passwordenv bw_master | pass insert --echo bw/bw_session
  fi
}
vault_login() {
  export "${1^^}"_ADDR="$(cred_cmd $1 addr "${2:-}")" && \
  $1 login -method=userpass username=$(cred_cmd $1 user "${2:-}") password="$(cred_cmd $1 passwd "${2:-}")"
}
az_login() {
  cred_check "$1" "${2:-}"
  az login --tenant "$(cred_cmd $1 tenant "${2:-}")"
}
ssh_add() {
  cred_check "$1" "${2:-}"
  if [[ -z ${3:-} ]]; then
    key_type=ed25519
  else
    key_type="${3:}"
  fi
  if [[ -z ${2:-} ]]; then
    echo "$(cred_cmd $1 passwd)" | head -n1 \
    | script -q -c "ssh-add $HOME/.ssh/key/sshk_"$key_type"" /dev/null
  elif [[ -f $HOME/.ssh/"${2:-}/sshk_ed25519" ]]; then
    echo "$(cred_cmd $1 passwd "${2:-}")" | head -n1 \
    | script -q -c "ssh-add $HOME/.ssh/key/"${2:-}"/sshk_"$key_type"" /dev/null
  else
    echo "ssh key missing from $HOME/.ssh/"${2:-}""
  fi
}
# FLOW
flow() {
  case $1 in
  az)
    az_login "$1" "${2:-}"
    ;;
  bao | vault)
    vault_login "$1" "${2:-}"
    ;;
  bw)
    bw_login "$1" "${2:-}"
    ;;
  ssh)
    ssh_add "$1" "${2:-}" "${3:-}"
    ;;
  *)
    echo 'ERROR: You need to provide value for $1'
    echo 'Usage: auth app profile* (*optional)'
    echo "possible values for app: "${!app_cred[@]}""
    ;;
  esac
}
flow "$1" "${2:-}" "${3:-}"
