#!/usr/bin/env zsh
BREW_PKGS=(
  aerc asdf az
  bat bitwarden-cli btop
  cmatrix cowsay
  eza
  fd figlet fzf
  git-crypt golang
  jq
  k9s kubectl
  lazygit lolcat
  most
  neovim newsboat nmap
  skopeo
  tmux tmuxp trivy
  weechat wego
  yq
  zoxide
)
if [[ ! ${1:-} == "update" ]]; then
  brew install $BREW_PKGS[@]
else
  brew update && brew upgrade
fi
