#!/usr/bin/env zsh
BREW_PKGS=(
  aerc
  az
  bat btop
  cowsay
  eza
  fd figlet fzf
  k9s kubectl
  lazygit lolcat
  most
  neomutt neovim newsboat nmap
  pyenv pyenv-virtualenv python-tk
  skopeo
  tenv tmux tmuxp trivy
  weechat
  zoxide
)
if [[ ! ${1:-} == "update" ]]; then
  brew install $BREW_PKGS[@]
else
  brew update && brew upgrade
fi
