#!/usr/bin/env bash
if [[ -z ${1:-} ]]; then
  ssh_key="ssh/sshk_ed25519"
else
  ssh_key="${1:-}"
fi
if ! pass "$ssh_key" &>/dev/null; then
  pass insert "$ssh_key"
else
  pass "$ssh_key" | head -n1 | script -q -c "ssh-add ~/.ssh/prv/sshk_ed25519" /dev/null
fi
