#!/usr/bin/env bash
# COMMON
ZSHDEP_COMMON=
  bat \
  eza \
  rustup \
  cargo \
  fd-find \
  golang \
  jq \
  kubectl \
  most \
  neomutt \
  neovim \
  nodejs \
  npm \
  pass \
  python3 \
  python3-pip \
  skopeo \
  tmux \
  trivy \
  vim \
  yq \
  zsh
)
#FEDORA
ZSHDEP_FEDORA=(
  zoxide \
  k9s \
)
# DEBIAN
ZSHDEP_DEBIAN=(
  bat \
)
ZSHDEP_ARCH=(
  base-devel \
  k9s \
  tofu \
  zoxide \
)
# INSTALL
if grep debian /etc/os-release; then
  sudo apt install -y $ZSHDEP_COMMON
  sudo apt install -y $ZSHDEP_DEBIAN
fi
if grep fedora /etc/os-release; then
  sudo dnf install -y $ZSHDEP_COMMON
  sudo dnf install -y $ZSHDEP_FEDORA
fi
