#!/usr/bin/env bash
set -euo pipefail
# DEPENDENCIES
## COMMON
ZSHDEP_COMMON=(
  autoconf automake awk
  bc
  ca-certificates calc cargo cmake curl
  dnsutils
  expect
  golang
  htop
  kitty-terminfo
  jq
  lsb-release
  nodejs npm
  p7zip perl python3 python3-neovim python3-pip
  rustup
  strace sudo-rs systemd-container
  tcpdump tmux
  util-linux
  vim
  wget whois
  yq
  zsh
)
## FEDORA
ZSHDEP_FEDORA=(
  net-tools
  util-linux-script
)
## DEBIAN
ZSHDEP_DEBIAN=(
  apt-transport-https
  bsdutils build-essential
  ncal
  software-properties-common
)
## ARCH
ZSHDEP_ARCH=(
  base-devel
)
## CARGO
ZSHDEP_CARGO=(
  wr
)
## NPM
ZSHDEP_NPM=(
  neovim
  n
  '@bitwarden/cli'
)
# HOMEBREW
brew_install() {
  if [[ ! -f /home/linuxbrew/.linuxbrew/bin/brew ]]; then
    CI=1 bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
}
yay_install() {
  if command -v yay &>/dev/null; then
    (git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si)
  fi
}
# BUILD FUNCTIONS
## NPM
npm_pkg_install() {
  if [[ ! ${1:-} == "update" ]]; then
    sudo npm install -g ${ZSHDEP_NPM[@]}
  else
    sudo npm update ${ZSHDEP_NPM[@]}
  fi
}
## CARGO
cargo_pkg_install() {
  export CARGO_HOME=$HOME/.local/share/cargo
  if [[ ! ${1:-} == "update" ]]; then
    cargo install ${ZSHDEP_CARGO[@]}
  else
    cargo install ${ZSHDEP_CARGO[@]} --force
  fi
}
ext_deps() {
  cargo_pkg_install ${1:-}
  npm_pkg_install ${1:-}
  brew_install ${1:-}
}
## DEBIAN
debian_install() {
  sudo apt install ${ZSHDEP_COMMON[@]}
  sudo apt install ${ZSHDEP_DEBIAN[@]}
  ext_deps ${1:-}
}
## FEDORA
fedora_install() {
  sudo dnf install ${ZSHDEP_COMMON[@]}
  sudo dnf install ${ZSHDEP_FEDORA[@]}
  ext_deps ${1:-}
}
## ARCH
arch_install() {
  sudo pacman -Syy ${ZSHDEP_COMMON[@]}
  sudo pacman -Syy ${ZSHDEP_ARCH[@]}
  ext_deps ${1:-}
  yay_install
}
flow() {
  if grep archlinux /etc/os-release &>/dev/null; then
    arch_install ${1:-}
  elif grep debian /etc/os-release &>/dev/null; then
    debian_install ${1:-}
  elif grep fedora /etc/os-release &>/dev/null; then
    fedora_install ${1:-}
  else
    echo "Unsupported OS"
  fi
  if [[ ! "$(grep "^$(whoami):" /etc/passwd | cut -d: -f7)" == "/bin/zsh" ]]; then
    sudo chsh -s /bin/zsh $(whoami)
  fi
}
if [[ -z ${1:-} ]] || [[ ${1:-} == "update" ]]; then
  flow ${1:-}
else
  echo 'Usage: zshdep update* (*optional)'
fi
